### PR TITLE
Prevent Prescription Quantity set to 1 

### LINKED ISSUE #172: Wrong Count of 1 When creating prescriptions
Providers are putting in a count of 1 for prescriptions (which is wrong). Checked the API request and we are getting 1 from them, just wanna be sure that our frontend isnt somehow making this 1

### PR DESCRIPTION
**Pull request by captDaylight**
If you select a medication rather than a treatment it should not automatically pass validation.

Screen Shot 2023-04-04 at 10 57 59 AM

closes #172

### CODE REVIEW

File: packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx [hunk 1]
```diff
@@ -212,7 +212,7 @@ export const AddPrescriptionCard = (props: {
           <photon-number-input
             class="flex-grow flex-shrink flex-1"
             label="Refills"
-            value={props.store['refillsInput']?.value ?? 0}
+            value={props.store['refillsInput']?.value ?? null}
```
Comment (samkotlove) [inline packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx:215]: This one I think we can leave as 0

File: packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx [hunk 2]
```diff
@@ -322,19 +322,19 @@ export const AddPrescriptionCard = (props: {
                   });
                   props.actions.updateFormValue({
                     key: 'refillsInput',
-                    value: 0
+                    value: null
```
Comment (samkotlove) [inline packages/elements/src/photon-multirx-form/components/AddPrescriptionCard.tsx:325]: same as above

**Review by samkotlove — APPROVED** [review]
1 small comment but looks good!
