### PR TITLE
Fix preferred pharmacy showing when fulfillment type not available

### LINKED ISSUE #329: Preferred pharmacies should respect available fulfillment types
"I believe it’s because the patient has a preferred pharmacy, which defaults. 
[@josh](https://photonhealth.slack.com/team/U0446QRT9QR)
 can we get this fixed in the AM? preferred pharmacies should respect what available pharmacy options there are" - sam

Screen Shot 2023-05-21 at 3 46 44 PM

### PR DESCRIPTION
**Pull request by jknapp25**
Closes #329 

https://github.com/Photon-Health/client/assets/3934326/22111a06-4c71-4e74-ada1-80423e65f11b

### CODE REVIEW

File: apps/app/src/views/routes/NewOrder/components/OrderForm.tsx [hunk 1]
```diff
@@ -143,19 +117,34 @@ export const OrderForm = ({
...
-   *  */
-  const preferredPharmacy =
-    patient?.preferredPharmacies?.length > 0 ? patient.preferredPharmacies[0] : null;
-  const initialFulfillmentType = sendToPatientEnabled
-    ? ''
-    : preferredPharmacy?.fulfillmentTypes.length > 0 ||
-      pharmacyOptions.findIndex((option) => option.enabled);
-  const initialPharmacyId = sendToPatientEnabled ? '' : preferredPharmacy?.id || '';
+  // Initialize fulfillment
+  let initialFulfillmentType: any = '';
```
Comment (captDaylight) [inline apps/app/src/views/routes/NewOrder/components/OrderForm.tsx:121]: `types.FulfillmentType | ''`?

**Review by captDaylight — APPROVED** [review]

File: apps/app/src/views/routes/NewOrder/components/OrderForm.tsx [hunk 2]
```diff
@@ -143,19 +117,34 @@ export const OrderForm = ({
...
+  let initialPharmacyId = '';
+
+  // Send to patient takes precedence over preferred pharmacy
+  if (!sendToPatientEnabled && (orgSettings.pickUp || orgSettings.mailOrder)) {
+    const preferredPharmacy = patient?.preferredPharmacies?.[0];
+
+    if (preferredPharmacy) {
+      // If preferred pharmacy has an enabled fulfillment type, make that the initial tab
+      const enabledTypes: string[] = fulfillmentOptions.reduce((acc: any, curr: any) => {
```
[the remark this answers is not in the document]
Comment (jknapp25) [reply apps/app/src/views/routes/NewOrder/components/OrderForm.tsx:130]: yeah worked great! ty!

File: apps/app/src/views/routes/NewOrder/components/OrderForm.tsx (hunk 1 above)
Comment (jknapp25) [reply apps/app/src/views/routes/NewOrder/components/OrderForm.tsx:121]: updated, thanks!
